// Host test for lib/hostframe (the pebble's side of brain/HOST_PROTOCOL.md): the lite frame and the checkpoint
// payload are parsed by the same code the pebble runs, and the auth digest + signature match what eth_account
// recovers as the body (fixtures/host_vectors.h, generated by tools/gen_host_vectors.py).
//   cd firmware && ../.venv/bin/pio test -e native -f test_host -v
#include <unity.h>
#include <string.h>
#include <math.h>
#include <string>
#include <vector>
#include "hostframe.h"
#include "ethtx.h"
#include "keccak.h"
#include "rpc.h"
#include "../../fixtures/host_vectors.h"
#include "../../fixtures/eth_vectors.h"

namespace rpc { extern bool (*mockCall)(const std::string&, const std::string&, std::string&); const char* lastError(); }
using namespace hostframe;

// Unity is built without double support here: compare doubles exactly through a delta
#define ASSERT_DOUBLE(expected, actual) TEST_ASSERT_TRUE_MESSAGE(fabs((double)(expected) - (double)(actual)) < 1e-6, #actual)

void setUp() {}
void tearDown() {}

// ---------------------------------------------------------------- the lite frame

static void test_frame_scalars() {
  LiteFrame f;
  TEST_ASSERT_TRUE(parseFrame(HOST_FRAME_JSON, strlen(HOST_FRAME_JSON), f));
  ASSERT_DOUBLE(HOST_FRAME_T_MS, f.t_ms);
  TEST_ASSERT_EQUAL_UINT64(HOST_FRAME_STEP, f.step);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_X, f.x);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_Y, f.y);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_HEADING, f.heading);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_ENERGY, f.energy);
  TEST_ASSERT_EQUAL(HOST_FRAME_ALIVE, f.alive ? 1 : 0);
  TEST_ASSERT_EQUAL_UINT32(HOST_FRAME_GENERATION, f.generation);
  TEST_ASSERT_EQUAL_UINT64(HOST_FRAME_SPIKES, f.spikesTotal);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_ATE, f.ate);
  TEST_ASSERT_EQUAL_UINT32(HOST_FRAME_JUMPS, f.jumps);
  TEST_ASSERT_EQUAL_UINT32(HOST_FRAME_HITS, f.hits);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_ARENA, f.arena);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_STEER, f.steer);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_REALTIME, f.realtime);
  ASSERT_DOUBLE(HOST_FRAME_WALL, f.wall);
  TEST_ASSERT_EQUAL_UINT32(HOST_FRAME_CHECKPOINTS, f.checkpoints);
  TEST_ASSERT_EQUAL_STRING(HOST_FRAME_MODE, f.modeText);
  TEST_ASSERT_EQUAL(M_SURGE, f.mode);
  TEST_ASSERT_EQUAL_STRING("following a scent", modeWord(f.mode));
}

static void test_frame_world() {
  LiteFrame f;
  TEST_ASSERT_TRUE(parseFrame(HOST_FRAME_JSON, strlen(HOST_FRAME_JSON), f));
  TEST_ASSERT_EQUAL(HOST_FRAME_NFOOD, f.nfood);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_FOOD0_X, f.food[0].x);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_FOOD0_Y, f.food[0].y);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_FOOD0_ENERGY, f.food[0].energy);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_FOOD0_ENERGY0, f.food[0].energy0);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_FOOD1_X, f.food[1].x);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_FOOD1_Y, f.food[1].y);
  TEST_ASSERT_TRUE(f.predator.present);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_PRED_X, f.predator.x);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_PRED_Y, f.predator.y);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_PRED_SIZE, f.predator.size);
  TEST_ASSERT_EQUAL(HOST_FRAME_NPUFFS, f.npuffs);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_PUFF0_X, f.puffs[0].x);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_PUFF0_Y, f.puffs[0].y);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_PUFF0_S, f.puffs[0].strength);
}

static void test_frame_rates() {
  LiteFrame f;
  TEST_ASSERT_TRUE(parseFrame(HOST_FRAME_JSON, strlen(HOST_FRAME_JSON), f));
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_DNA02_L, f.rates.dna02L);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_DNA02_R, f.rates.dna02R);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_ALPN, f.rates.alpn);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_KC, f.rates.kc);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_MBON, f.rates.mbon);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_LC4_L, f.rates.lc4L);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_LC4_R, f.rates.lc4R);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_GRN, f.rates.grn);
  TEST_ASSERT_EQUAL_FLOAT(HOST_FRAME_DN_ALL, f.rates.dnAll);
}

static void test_frame_events_keep_the_newest() {
  LiteFrame f;
  TEST_ASSERT_TRUE(parseFrame(HOST_FRAME_JSON, strlen(HOST_FRAME_JSON), f));
  TEST_ASSERT_EQUAL(12, HOST_FRAME_NEVENTS_TOTAL);
  TEST_ASSERT_EQUAL(MAX_EVENTS, f.nevents);
  ASSERT_DOUBLE(HOST_FRAME_EVENT_FIRSTKEPT6_T, f.events[0].t_ms);
  TEST_ASSERT_EQUAL_STRING(HOST_FRAME_EVENT_FIRSTKEPT6_TEXT, f.events[0].text);
  ASSERT_DOUBLE(HOST_FRAME_EVENT_LAST_T, f.events[MAX_EVENTS - 1].t_ms);
  TEST_ASSERT_EQUAL_STRING(HOST_FRAME_EVENT_LAST_TEXT, f.events[MAX_EVENTS - 1].text);
  TEST_ASSERT_EQUAL(2, eventSound(f.events[MAX_EVENTS - 1].text));   // "giant fiber spike: jumped" -> blip
  TEST_ASSERT_EQUAL(1, eventSound("finished a food item worth 600s"));
  TEST_ASSERT_EQUAL(3, eventSound("caught by the predator: -60 s"));
  TEST_ASSERT_EQUAL(0, eventSound("smelled food"));
  TEST_ASSERT_EQUAL(0, eventSound("a shadow approaches"));
}

static void test_frame_minimal_and_dead() {
  LiteFrame f;
  const char* j = "{\"x\":1,\"y\":2,\"heading\":0.5,\"energy\":0,\"alive\":false,\"mode\":\"walk\",\"predator\":null,\"food\":[],\"events\":[]}";
  TEST_ASSERT_TRUE(parseFrame(j, strlen(j), f));
  TEST_ASSERT_FALSE(f.alive);
  TEST_ASSERT_FALSE(f.predator.present);
  TEST_ASSERT_EQUAL(0, f.nfood);
  TEST_ASSERT_EQUAL(0, f.npuffs);
  TEST_ASSERT_EQUAL(0, f.nevents);
  TEST_ASSERT_EQUAL(M_WANDER, f.mode);                 // the world's "walk" is the protocol's "wander"
  TEST_ASSERT_EQUAL_FLOAT(240.f, f.arena);             // default when absent
  TEST_ASSERT_EQUAL_FLOAT(0.f, f.rates.alpn);
  const char* still = "{\"x\":0,\"y\":0,\"alive\":true,\"mode\":\"still\"}";
  TEST_ASSERT_TRUE(parseFrame(still, strlen(still), f));
  TEST_ASSERT_EQUAL(M_STILL, f.mode);
  TEST_ASSERT_EQUAL_STRING("still", modeWord(f.mode));
  TEST_ASSERT_EQUAL(M_UNKNOWN, modeFromText("levitate"));
}

static void test_frame_caps_and_rejects() {
  // more food / puffs than the struct holds: the first MAX are kept, nothing overflows
  std::string j = "{\"x\":0,\"y\":0,\"alive\":true,\"food\":[";
  for (int i = 0; i < 12; ++i) { if (i) j += ","; j += "{\"x\":" + std::to_string(i) + ",\"y\":0,\"energy\":1,\"energy0\":1}"; }
  j += "],\"puffs\":[";
  for (int i = 0; i < 7; ++i) { if (i) j += ","; j += "{\"x\":" + std::to_string(i) + ",\"y\":1}"; }
  j += "]}";
  LiteFrame f;
  TEST_ASSERT_TRUE(parseFrame(j.c_str(), j.size(), f));
  TEST_ASSERT_EQUAL(MAX_FOOD, f.nfood);
  TEST_ASSERT_EQUAL_FLOAT(7.f, f.food[7].x);
  TEST_ASSERT_EQUAL(MAX_PUFFS, f.npuffs);
  TEST_ASSERT_EQUAL_FLOAT(1.f, f.puffs[0].strength);   // strength omitted -> 1
  // not a frame
  TEST_ASSERT_FALSE(parseFrame("{\"hdr\":{}}", 9, f));
  TEST_ASSERT_FALSE(parseFrame("[1,2,3]", 7, f));
  TEST_ASSERT_FALSE(parseFrame("{\"x\":1,\"alive\":true", 18, f));   // truncated
  TEST_ASSERT_FALSE(parseFrame(nullptr, 0, f));
}

// ---------------------------------------------------------------- the checkpoint / final payload

static void test_payload_fields() {
  Payload p;
  TEST_ASSERT_TRUE(parsePayload(HOST_PAYLOAD_JSON, strlen(HOST_PAYLOAD_JSON), p));
  TEST_ASSERT_EQUAL_MEMORY(HOST_PAYLOAD_STATE_ROOT, p.stateRoot, 32);
  TEST_ASSERT_EQUAL_MEMORY(HOST_PAYLOAD_MEMORY_ROOT, p.memoryRoot, 32);
  TEST_ASSERT_EQUAL_MEMORY(HOST_PAYLOAD_HISTORY_ROOT, p.historyRoot, 32);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_STATE_URI, p.stateURI.c_str());
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_META_URI, p.metadataURI.c_str());
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_BRAIN_STEP, p.brainStep);
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_ENERGY, p.energy);
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_AGE_S, p.age_s);
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_SPIKES, p.spikes);
  TEST_ASSERT_EQUAL_UINT32(HOST_PAYLOAD_GENERATION, p.generation);
  TEST_ASSERT_EQUAL_STRING("", p.cause.c_str());
}

static void test_payload_interactions_newest_first() {
  Payload p;
  TEST_ASSERT_TRUE(parsePayload(HOST_PAYLOAD_JSON, strlen(HOST_PAYLOAD_JSON), p));
  TEST_ASSERT_EQUAL(HOST_PAYLOAD_NINTER, p.listed);
  TEST_ASSERT_EQUAL(HOST_PAYLOAD_NINTER, p.ninteractions);
  ASSERT_DOUBLE(HOST_PAYLOAD_INTER0_T, p.interactions[0].t_ms);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER0_KIND, p.interactions[0].kind);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER0_DATA, p.interactions[0].data);
  ASSERT_DOUBLE(HOST_PAYLOAD_INTER1_T, p.interactions[1].t_ms);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER1_KIND, p.interactions[1].kind);
  ASSERT_DOUBLE(HOST_PAYLOAD_INTER2_T, p.interactions[2].t_ms);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER2_KIND, p.interactions[2].kind);
  ASSERT_DOUBLE(HOST_PAYLOAD_INTER3_T, p.interactions[3].t_ms);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER3_KIND, p.interactions[3].kind);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER3_DATA, p.interactions[3].data);
  for (int i = 1; i < p.ninteractions; ++i) TEST_ASSERT_TRUE(p.interactions[i - 1].t_ms >= p.interactions[i].t_ms);
}

static void test_payload_final_and_rejects() {
  Payload p;
  TEST_ASSERT_TRUE(parsePayload(HOST_FINAL_JSON, strlen(HOST_FINAL_JSON), p));
  TEST_ASSERT_EQUAL_STRING(HOST_FINAL_CAUSE, p.cause.c_str());
  TEST_ASSERT_EQUAL_UINT64(HOST_FINAL_BRAIN_STEP, p.brainStep);
  TEST_ASSERT_EQUAL_UINT64(0, p.energy);
  // twelve interactions: the newest MAX_INTERACTIONS survive, in order
  std::string j = "{\"stateRoot\":\"0x" + std::string(64, 'a') + "\",\"memoryRoot\":\"0x" + std::string(64, 'b') + "\",\"stateURI\":\"ipfs://x\",\"brainStep\":5,\"interactions\":[";
  for (int i = 0; i < 12; ++i) { if (i) j += ","; j += "{\"t_ms\":" + std::to_string(1000 * i) + ",\"kind\":\"ate\",\"data\":\"n" + std::to_string(i) + "\"}"; }
  j += "]}";
  TEST_ASSERT_TRUE(parsePayload(j.c_str(), j.size(), p));
  TEST_ASSERT_EQUAL(12, p.listed);
  TEST_ASSERT_EQUAL(MAX_INTERACTIONS, p.ninteractions);
  ASSERT_DOUBLE(11000.0, p.interactions[0].t_ms);
  TEST_ASSERT_EQUAL_STRING("n11", p.interactions[0].data);
  ASSERT_DOUBLE(4000.0, p.interactions[MAX_INTERACTIONS - 1].t_ms);
  TEST_ASSERT_EQUAL_STRING("", p.metadataURI.c_str());
  for (int i = 0; i < 32; ++i) TEST_ASSERT_EQUAL_UINT8(0, p.historyRoot[i]);   // absent -> zero
  // missing / malformed required fields
  const char* noRoot = "{\"memoryRoot\":\"0x00\",\"stateURI\":\"ipfs://x\",\"brainStep\":1}";
  TEST_ASSERT_FALSE(parsePayload(noRoot, strlen(noRoot), p));
  std::string shortRoot = "{\"stateRoot\":\"0xabc\",\"memoryRoot\":\"0x" + std::string(64, 'b') + "\",\"stateURI\":\"ipfs://x\",\"brainStep\":1}";
  TEST_ASSERT_FALSE(parsePayload(shortRoot.c_str(), shortRoot.size(), p));
  std::string noUri = "{\"stateRoot\":\"0x" + std::string(64, 'a') + "\",\"memoryRoot\":\"0x" + std::string(64, 'b') + "\",\"brainStep\":1}";
  TEST_ASSERT_FALSE(parsePayload(noUri.c_str(), noUri.size(), p));
  std::string noStep = "{\"stateRoot\":\"0x" + std::string(64, 'a') + "\",\"memoryRoot\":\"0x" + std::string(64, 'b') + "\",\"stateURI\":\"ipfs://x\"}";
  TEST_ASSERT_FALSE(parsePayload(noStep.c_str(), noStep.size(), p));
  TEST_ASSERT_FALSE(parsePayload("{\"error\":\"not the body\"}", 26, p));
}

// ---------------------------------------------------------------- the held checkpoint (commit retry)

static void test_held_payload_is_resent_until_the_chain_has_it() {
  Payload p;
  TEST_ASSERT_TRUE(parsePayload(HOST_PAYLOAD_JSON, strlen(HOST_PAYLOAD_JSON), p));
  Held h;
  TEST_ASSERT_FALSE(h.active);
  TEST_ASSERT_FALSE(h.pending(0));
  h.take(p, 1000);
  TEST_ASSERT_TRUE(h.active);
  TEST_ASSERT_EQUAL_UINT8(0, h.sends);
  // the copy is the payload: roots, uris, step, the interactions newest first
  TEST_ASSERT_EQUAL_UINT8_ARRAY(p.stateRoot, h.p.stateRoot, 32);
  TEST_ASSERT_EQUAL_UINT8_ARRAY(p.historyRoot, h.p.historyRoot, 32);
  TEST_ASSERT_EQUAL_STRING(p.stateURI.c_str(), h.p.stateURI.c_str());
  TEST_ASSERT_EQUAL_STRING(p.metadataURI.c_str(), h.p.metadataURI.c_str());
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_BRAIN_STEP, h.p.brainStep);
  TEST_ASSERT_EQUAL(HOST_PAYLOAD_NINTER, h.p.ninteractions);
  TEST_ASSERT_EQUAL_STRING(HOST_PAYLOAD_INTER0_DATA, h.p.interactions[0].data);
  // pending while the chain's brainStep is below the payload's; landed (or superseded) once it is at or past it
  TEST_ASSERT_TRUE(h.pending(HOST_PAYLOAD_BRAIN_STEP - 1));
  TEST_ASSERT_TRUE(h.pending(0));
  TEST_ASSERT_FALSE(h.pending(HOST_PAYLOAD_BRAIN_STEP));
  TEST_ASSERT_FALSE(h.pending(HOST_PAYLOAD_BRAIN_STEP + 5));
  // the energy is the host's value drained by the whole seconds since the fetch, never below 0
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_ENERGY, h.energyAt(1000));
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_ENERGY, h.energyAt(1999));
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_ENERGY - 1, h.energyAt(2000));
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_ENERGY - 90, h.energyAt(1000 + 90 * 1000));
  TEST_ASSERT_EQUAL_UINT64(0, h.energyAt(1000 + (uint32_t)HOST_PAYLOAD_ENERGY * 1000));
  TEST_ASSERT_EQUAL_UINT64(0, h.energyAt(1000 + (uint32_t)HOST_PAYLOAD_ENERGY * 1000 + 5000));
  // across the millis() rollover
  h.take(p, 0xFFFFFFFFu - 500);
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_ENERGY - 2, h.energyAt(1500));
  // a new fetch replaces it; clear() drops it
  Payload q = p; q.brainStep = HOST_PAYLOAD_BRAIN_STEP + 1000; q.energy = 5;
  h.take(q, 7000);
  TEST_ASSERT_EQUAL_UINT64(HOST_PAYLOAD_BRAIN_STEP + 1000, h.p.brainStep);
  TEST_ASSERT_TRUE(h.pending(HOST_PAYLOAD_BRAIN_STEP));
  h.sends = 2; h.reverts = 1;
  h.clear();
  TEST_ASSERT_FALSE(h.active);
  TEST_ASSERT_FALSE(h.pending(0));
  TEST_ASSERT_EQUAL_UINT8(0, h.sends);
  TEST_ASSERT_EQUAL_UINT8(0, h.reverts);
}

static void test_commit_due_retries_a_failed_send_early() {
  const uint32_t every = 600000, retry = 60000;
  // the regular cadence, nothing held
  TEST_ASSERT_FALSE(commitDue(100000, 100000, every, false, retry));
  TEST_ASSERT_FALSE(commitDue(100000 + every - 1, 100000, every, false, retry));
  TEST_ASSERT_TRUE(commitDue(100000 + every, 100000, every, false, retry));
  // a held payload whose send failed: retryMs after the attempt
  TEST_ASSERT_FALSE(commitDue(100000 + retry - 1, 100000, every, true, retry));
  TEST_ASSERT_TRUE(commitDue(100000 + retry, 100000, every, true, retry));
  TEST_ASSERT_TRUE(commitDue(100000 + every, 100000, every, true, retry));
  // a sent commit that awaits its receipt is not retried early (the caller passes retry = false)
  TEST_ASSERT_FALSE(commitDue(100000 + every - 1, 100000, every, false, retry));
  // rollover
  TEST_ASSERT_TRUE(commitDue(retry - 10, 0xFFFFFFFFu - 10, every, true, retry));
  TEST_ASSERT_FALSE(commitDue(retry - 12, 0xFFFFFFFFu - 10, every, true, retry));
}

// ---------------------------------------------------------------- auth

static void test_auth_message_and_digest() {
  char msg[64];
  size_t n = authMessage(HOST_AUTH_ID, HOST_AUTH_TS, msg, sizeof msg);
  TEST_ASSERT_EQUAL_STRING(HOST_AUTH_MESSAGE, msg);
  TEST_ASSERT_EQUAL(strlen(HOST_AUTH_MESSAGE), n);
  uint8_t d[32];
  authDigest(HOST_AUTH_ID, HOST_AUTH_TS, d);
  TEST_ASSERT_EQUAL_MEMORY(HOST_AUTH_DIGEST, d, 32);
  // the digest is keccak256 of the ascii text, no EIP-191 prefix
  uint8_t k[32]; keccak256((const uint8_t*)HOST_AUTH_MESSAGE, strlen(HOST_AUTH_MESSAGE), k);
  TEST_ASSERT_EQUAL_MEMORY(k, d, 32);
}

static void test_auth_signature_matches_eth_account() {
  uint8_t sig[65];
  TEST_ASSERT_TRUE(authSign(HOST_AUTH_ID, HOST_AUTH_TS, ETH_TEST_PRIV, sig));
  TEST_ASSERT_EQUAL_MEMORY(HOST_AUTH_SIG, sig, 65);            // r || s || v, deterministic (RFC 6979)
  TEST_ASSERT_TRUE(sig[64] == 27 || sig[64] == 28);
  TEST_ASSERT_EQUAL_STRING(HOST_AUTH_SIG_HEX, authSigHex(sig).c_str());
  TEST_ASSERT_EQUAL(132, (int)authSigHex(sig).size());
  // the signer eth_account recovers is the test wallet: the pebble proves it is the body
  TEST_ASSERT_EQUAL_MEMORY(ETH_TEST_ADDR, HOST_AUTH_RECOVERED_BYTES, 20);
  TEST_ASSERT_EQUAL_STRING(ETH_TEST_ADDR_CHECKSUM, HOST_AUTH_RECOVERED);
  // the signature is over the digest: r||s equal signDigest's, v is 27 + recid
  uint8_t d[32], rs[64]; uint8_t recid = 9;
  authDigest(HOST_AUTH_ID, HOST_AUTH_TS, d);
  TEST_ASSERT_TRUE(ethtx::signDigest(d, ETH_TEST_PRIV, rs, &recid));
  TEST_ASSERT_EQUAL_MEMORY(rs, sig, 64);
  TEST_ASSERT_EQUAL_UINT8(27 + recid, sig[64]);
  // a different ts is a different signature
  uint8_t sig2[65];
  TEST_ASSERT_TRUE(authSign(HOST_AUTH_ID, HOST_AUTH_TS + 1, ETH_TEST_PRIV, sig2));
  TEST_ASSERT_TRUE(memcmp(sig, sig2, 64) != 0);
}

static void test_http_date() {
  ASSERT_DOUBLE(0.0, httpDate("Thu, 01 Jan 1970 00:00:00 GMT"));
  ASSERT_DOUBLE(1789500000.0, httpDate("Tue, 15 Sep 2026 19:20:00 GMT"));   // python: datetime.utcfromtimestamp(1789500000)
  ASSERT_DOUBLE(951782400.0, httpDate("Tue, 29 Feb 2000 00:00:00 GMT"));    // leap day
  ASSERT_DOUBLE(1700000000.0, httpDate("Tue, 14 Nov 2023 22:13:20 GMT"));
  ASSERT_DOUBLE(0.0, httpDate("nonsense"));
  ASSERT_DOUBLE(0.0, httpDate(nullptr));
}

// ---------------------------------------------------------------- bodies(address) through lib/rpc

static std::string s_lastParams;
static bool mockBodies(const std::string& method, const std::string& params, std::string& out) {
  s_lastParams = params;
  if (method != "eth_call") return false;
  out = "\"" + ethtx::toHex(HOST_BODIES_RET, sizeof HOST_BODIES_RET) + "\"";
  return true;
}

static void test_bodies_wrapper_finds_the_host_uri() {
  rpc::Client client; client.url = "https://mock";
  rpc::mockCall = mockBodies;
  rpc::Registry reg(client, "0x0eeB0A675720306Ef6f426Bd8560c1288848f813");
  uint8_t host[20]; ethtx::Bytes b; TEST_ASSERT_TRUE(ethtx::fromHex("0x4fC3E7D1fAD1A8E7FAC849DAa5BfF0C8333fe2a6", b)); memcpy(host, b.data(), 20);
  std::string name, uri; uint64_t block = 0; uint32_t flies = 0;
  TEST_ASSERT_TRUE(reg.body(host, name, uri, &block, &flies));
  TEST_ASSERT_EQUAL_STRING(HOST_BODIES_NAME, name.c_str());
  TEST_ASSERT_EQUAL_STRING(HOST_BODIES_URI, uri.c_str());
  TEST_ASSERT_EQUAL_UINT64(HOST_BODIES_BLOCK, block);
  TEST_ASSERT_EQUAL_UINT32(HOST_BODIES_FLIES, flies);
  // calldata: selector of bodies(address) + the padded address
  uint8_t sel[32]; const char* sig = "bodies(address)"; keccak256((const uint8_t*)sig, strlen(sig), sel);
  std::string want = ethtx::toHex(sel, 4) + std::string(24, '0') + "4fc3e7d1fad1a8e7fac849daa5bff0c8333fe2a6";
  TEST_ASSERT_TRUE(s_lastParams.find(want) != std::string::npos);
  rpc::mockCall = nullptr;
}

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_frame_scalars);
  RUN_TEST(test_frame_world);
  RUN_TEST(test_frame_rates);
  RUN_TEST(test_frame_events_keep_the_newest);
  RUN_TEST(test_frame_minimal_and_dead);
  RUN_TEST(test_frame_caps_and_rejects);
  RUN_TEST(test_payload_fields);
  RUN_TEST(test_payload_interactions_newest_first);
  RUN_TEST(test_payload_final_and_rejects);
  RUN_TEST(test_held_payload_is_resent_until_the_chain_has_it);
  RUN_TEST(test_commit_due_retries_a_failed_send_early);
  RUN_TEST(test_auth_message_and_digest);
  RUN_TEST(test_auth_signature_matches_eth_account);
  RUN_TEST(test_http_date);
  RUN_TEST(test_bodies_wrapper_finds_the_host_uri);
  return UNITY_END();
}
