// The fly, from brand/fly.txt (generated by hand for the boot screen). 15 lines, 57 columns.
#pragma once
static const int FLYART_LINES = 15;
static const int FLYART_COLS = 57;
static const char* const FLYART[15] = {
  "                       \\   /",
  "                .--.    \\ /    .--.",
  "               ( @@ )-.-`-'-.-( @@ )",
  "                `--'  `.___,'  `--'",
  "           ___________  ,-'\"`-.  ___________",
  "     _,-'\"            `/       \\'            \"`-._",
  " _,-'      .       .   \\       /   .       .      `-._",
  "'     .        .        `-.|.-'        .        .     `",
  "(   .       .       .    (=|||=)    .       .       .   )",
  " `-._    .        .       `|||'       .        .     _,-'",
  "     `-._      .      _,-'=|||=`-._      .       _,-'",
  "         `-.______,-'     =|||=    `-.______,-'",
  "                          =|||=",
  "                           `|'",
  "                            '",
};
