// Host test for lib/ethtx: signatures, transactions and ABI bytes must equal what eth_account / eth_keys / eth_abi
// produce for the same inputs (fixtures/eth_vectors.h, generated by tools/gen_eth_vectors.py).
#include <unity.h>
#include <string.h>
#include <string>
#include "ethtx.h"
#include "keccak.h"
#include "../../fixtures/eth_vectors.h"

using ethtx::Bytes;

void setUp(void) {}
void tearDown(void) {}

static Bytes bytesOf(const uint8_t* b, size_t n) { return Bytes(b, b + n); }

// ---------------------------------------------------------------- keys, addresses, hex

static void test_address_from_private_key(void) {
  uint8_t addr[20];
  TEST_ASSERT_TRUE(ethtx::privateKeyToAddress(ETH_TEST_PRIV, addr));
  TEST_ASSERT_EQUAL_MEMORY(ETH_TEST_ADDR, addr, 20);
  TEST_ASSERT_EQUAL_STRING(ETH_TEST_ADDR_LOWER, ethtx::toHex(addr, 20).c_str());
  TEST_ASSERT_EQUAL_STRING(ETH_TEST_ADDR_LOWER + 2, ethtx::toHex(addr, 20, false).c_str());
}

static void test_checksum_address(void) {
  TEST_ASSERT_EQUAL_STRING(ETH_TEST_ADDR_CHECKSUM, ethtx::checksumAddress(ETH_TEST_ADDR).c_str());
  // EIP-55 reference vectors
  Bytes a;
  TEST_ASSERT_TRUE(ethtx::fromHex("0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed", a));
  TEST_ASSERT_EQUAL_STRING("0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed", ethtx::checksumAddress(a.data()).c_str());
  TEST_ASSERT_TRUE(ethtx::fromHex("0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359", a));
  TEST_ASSERT_EQUAL_STRING("0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359", ethtx::checksumAddress(a.data()).c_str());
  TEST_ASSERT_TRUE(ethtx::fromHex("dbf03b407c01e7cd3cbea99509d93f8dddc8c6fb", a));
  TEST_ASSERT_EQUAL_STRING("0xdbF03B407c01E7cD3CBea99509d93f8DDDC8C6FB", ethtx::checksumAddress(a.data()).c_str());
}

static void test_invalid_private_keys(void) {
  uint8_t zero[32] = {0}, addr[20];
  TEST_ASSERT_FALSE(ethtx::privateKeyToAddress(zero, addr));
  Bytes n;  // the group order is not a valid key
  TEST_ASSERT_TRUE(ethtx::fromHex("fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141", n));
  TEST_ASSERT_EQUAL(32, n.size());
  TEST_ASSERT_FALSE(ethtx::privateKeyToAddress(n.data(), addr));
  uint8_t sig[64], recid;
  TEST_ASSERT_FALSE(ethtx::signDigest(ETH_SIG_VECTORS[0].digest, zero, sig, &recid));
  TEST_ASSERT_FALSE(ethtx::signDigest(zero, ETH_TEST_PRIV, sig, &recid));   // an all-zero digest is refused
}

static void test_hex(void) {
  Bytes b;
  TEST_ASSERT_TRUE(ethtx::fromHex("0xabc", b));
  TEST_ASSERT_EQUAL(2, b.size()); TEST_ASSERT_EQUAL_HEX8(0x0a, b[0]); TEST_ASSERT_EQUAL_HEX8(0xbc, b[1]);
  TEST_ASSERT_TRUE(ethtx::fromHex("ABCD", b));
  TEST_ASSERT_EQUAL(2, b.size()); TEST_ASSERT_EQUAL_HEX8(0xab, b[0]); TEST_ASSERT_EQUAL_HEX8(0xcd, b[1]);
  TEST_ASSERT_TRUE(ethtx::fromHex("0x", b)); TEST_ASSERT_EQUAL(0, b.size());
  TEST_ASSERT_TRUE(ethtx::fromHex("", b)); TEST_ASSERT_EQUAL(0, b.size());
  TEST_ASSERT_FALSE(ethtx::fromHex("0x12g4", b));
  TEST_ASSERT_TRUE(ethtx::fromHex(ETH_TEST_ADDR_CHECKSUM, b));
  TEST_ASSERT_EQUAL_MEMORY(ETH_TEST_ADDR, b.data(), 20);
  TEST_ASSERT_EQUAL_STRING("0x00ff10", ethtx::toHex((const uint8_t*)"\x00\xff\x10", 3).c_str());
}

// ---------------------------------------------------------------- signatures

static void test_sign_digest_vectors(void) {
  for (size_t i = 0; i < sizeof(ETH_SIG_VECTORS) / sizeof(ETH_SIG_VECTORS[0]); i++) {
    const EthSigVector& v = ETH_SIG_VECTORS[i];
    uint8_t sig[64] = {0}; uint8_t recid = 9;
    TEST_ASSERT_TRUE_MESSAGE(ethtx::signDigest(v.digest, ETH_TEST_PRIV, sig, &recid), "signDigest failed");
    TEST_ASSERT_EQUAL_MEMORY_MESSAGE(v.r, sig, 32, "r");
    TEST_ASSERT_EQUAL_MEMORY_MESSAGE(v.s, sig + 32, 32, "s");
    TEST_ASSERT_EQUAL_UINT8_MESSAGE(v.recid, recid, "recid");
    // deterministic (RFC 6979): the same digest signs to the same bytes again
    uint8_t sig2[64]; uint8_t recid2;
    TEST_ASSERT_TRUE(ethtx::signDigest(v.digest, ETH_TEST_PRIV, sig2, &recid2));
    TEST_ASSERT_EQUAL_MEMORY(sig, sig2, 64);
    TEST_ASSERT_EQUAL_UINT8(recid, recid2);
  }
}

static void test_sign_tx_vectors(void) {
  for (size_t i = 0; i < sizeof(ETH_TX_VECTORS) / sizeof(ETH_TX_VECTORS[0]); i++) {
    const EthTxVector& v = ETH_TX_VECTORS[i];
    ethtx::Tx tx;
    tx.nonce = v.nonce; tx.gasPrice = v.gasPrice; tx.gas = v.gas; memcpy(tx.to, v.to, 20); tx.value = v.value;
    tx.data = bytesOf(v.data, v.dataLen); tx.chainId = ETH_CHAIN_ID;
    Bytes raw; uint8_t hash[32];
    TEST_ASSERT_TRUE_MESSAGE(ethtx::sign(tx, ETH_TEST_PRIV, raw, hash), v.name);
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(v.rawLen, raw.size(), v.name);
    TEST_ASSERT_EQUAL_MEMORY_MESSAGE(v.raw, raw.data(), v.rawLen, v.name);
    TEST_ASSERT_EQUAL_MEMORY_MESSAGE(v.hash, hash, 32, v.name);
    // the hash is keccak(raw) and v is 147/148 (chain 56); the raw tx must start with an RLP list header
    uint8_t h2[32]; keccak256(raw.data(), raw.size(), h2);
    TEST_ASSERT_EQUAL_MEMORY(hash, h2, 32);
    TEST_ASSERT_TRUE(raw[0] >= 0xc0);
    TEST_ASSERT_TRUE(v.v == 147 || v.v == 148);
  }
}

static void test_sign_tx_default_chain_and_sender(void) {
  // Tx defaults: value 0, chainId 56. Signing tx 1 (nonce 0, empty data) through the defaults gives the same bytes.
  const EthTxVector& v = ETH_TX_VECTORS[1];
  ethtx::Tx tx; tx.nonce = v.nonce; tx.gasPrice = v.gasPrice; tx.gas = v.gas; memcpy(tx.to, v.to, 20);
  Bytes raw; uint8_t hash[32];
  TEST_ASSERT_TRUE(ethtx::sign(tx, ETH_TEST_PRIV, raw, hash));
  TEST_ASSERT_EQUAL_MEMORY(v.raw, raw.data(), v.rawLen);
  // a different chain id changes v and the signature
  tx.chainId = 97; Bytes raw2;
  TEST_ASSERT_TRUE(ethtx::sign(tx, ETH_TEST_PRIV, raw2, nullptr));
  TEST_ASSERT_TRUE(raw2 != raw);
}

// ---------------------------------------------------------------- ABI encoding

#define ASSERT_ABI(expected, actual) do { Bytes a_ = (actual); \
  TEST_ASSERT_EQUAL_UINT32_MESSAGE(sizeof(expected), a_.size(), #expected " length"); \
  TEST_ASSERT_EQUAL_MEMORY_MESSAGE(expected, a_.data(), sizeof(expected), #expected); } while (0)

static void test_abi_register_body(void) {
  ASSERT_ABI(ABI_REGISTERBODY, ethtx::AbiEncoder("registerBody(string,string)").string(ABI_NAME).string(ABI_URI).finish());
}

static void test_abi_accept(void) {
  ASSERT_ABI(ABI_ACCEPT, ethtx::AbiEncoder("accept(uint256)").uint(1).finish());
}

static void test_abi_interaction(void) {
  ASSERT_ABI(ABI_INTERACTION, ethtx::AbiEncoder("interaction(uint256,bytes32,string)").uint(1).bytes32(ABI_KIND).string(ABI_INTER_DATA).finish());
  uint8_t zero[32] = {0};
  ASSERT_ABI(ABI_INTERACTION_EMPTY, ethtx::AbiEncoder("interaction(uint256,bytes32,string)").uint(UINT64_MAX).bytes32(zero).string("").finish());
}

static void test_abi_commit(void) {
  ASSERT_ABI(ABI_COMMIT, ethtx::AbiEncoder("commit(uint256,bytes32,bytes32,string,string,uint64,uint64,bytes32)")
                             .uint(1).bytes32(ABI_STATE_ROOT).bytes32(ABI_MEM_ROOT).string(ABI_STATE_URI).string(ABI_META_URI)
                             .uint(ABI_STEP).uint(ABI_ENERGY).bytes32(ABI_HIST_ROOT).finish());
}

static void test_abi_stimulate(void) {
  ASSERT_ABI(ABI_STIMULATE, ethtx::AbiEncoder("stimulate(uint256,uint8,uint8,uint8,uint16)").uint(1).uint(3).uint(12).uint(200).uint(65535).finish());
}

static void test_abi_address_bytes_int(void) {
  ASSERT_ABI(ABI_ASSIGN, ethtx::AbiEncoder("assign(uint256,address)").uint(1).address(ETH_TEST_ADDR).finish());
  ASSERT_ABI(ABI_FEED_BYTES, ethtx::AbiEncoder("debug(bytes,int32)").bytes(bytesOf(ABI_BYTES33, 33)).int_(ABI_INT32_NEG).finish());
  // uint256 from a full word, and int_ sign extension
  uint8_t word[32] = {0}; word[31] = 1;
  Bytes e = ethtx::AbiEncoder("accept(uint256)").uint256(word).finish();
  TEST_ASSERT_EQUAL_MEMORY(ABI_ACCEPT, e.data(), sizeof(ABI_ACCEPT));
  Bytes neg = ethtx::AbiEncoder("x(int8)").int_(-1).finish();
  TEST_ASSERT_EQUAL(36, neg.size());
  for (int i = 4; i < 36; i++) TEST_ASSERT_EQUAL_HEX8(0xff, neg[i]);
  Bytes pos = ethtx::AbiEncoder("x(int8)").int_(5).finish();
  TEST_ASSERT_EQUAL_HEX8(0x00, pos[4]); TEST_ASSERT_EQUAL_HEX8(0x05, pos[35]);
}

static void test_abi_selector(void) {
  Bytes e = ethtx::AbiEncoder("tick(uint256,uint16)").uint(1).uint(16).finish();
  TEST_ASSERT_EQUAL(68, e.size());
  TEST_ASSERT_EQUAL_MEMORY(ETH_TX0_DATA, e.data(), 68);   // tx 0's calldata was built by eth_abi from the same call
  Bytes t = ethtx::AbiEncoder("transfer(address,uint256)").finish();
  TEST_ASSERT_EQUAL(4, t.size());
  TEST_ASSERT_EQUAL_HEX8(0xa9, t[0]); TEST_ASSERT_EQUAL_HEX8(0x05, t[1]); TEST_ASSERT_EQUAL_HEX8(0x9c, t[2]); TEST_ASSERT_EQUAL_HEX8(0xbb, t[3]);
}

// ---------------------------------------------------------------- ABI decoding

static void test_abi_decode_core(void) {
  Bytes ret = bytesOf(CORE_RET, sizeof CORE_RET);
  ethtx::AbiDecoder d(ret);
  TEST_ASSERT_EQUAL_UINT32(sizeof(CORE_RET) / 32, d.words());
  // head: [0] off v, [1] off bias, [2..17] hist inline, [18] off inp, [19] step, [20] headX, [21] headY, [22] posX, [23] posY,
  //       [24] stimChannel, [25] stimParam, [26] stimStrength, [27] stimUntilStep
  TEST_ASSERT_EQUAL_UINT32(CORE_N, d.arrayLen(0));
  for (size_t i = 0; i < CORE_N; i++) TEST_ASSERT_EQUAL_INT64(CORE_V[i], d.arrayInt(0, i));
  TEST_ASSERT_EQUAL_UINT32(CORE_N, d.arrayLen(1));
  for (size_t i = 0; i < CORE_N; i++) TEST_ASSERT_EQUAL_INT64(CORE_BIAS[i], d.arrayInt(1, i));
  for (size_t w = 0; w < 16; w++) TEST_ASSERT_EQUAL_UINT64(CORE_HIST[w], d.uint(2 + w));
  TEST_ASSERT_EQUAL_UINT32(CORE_N, d.arrayLen(18));
  for (size_t i = 0; i < CORE_N; i++) TEST_ASSERT_EQUAL_INT64(CORE_INP[i], d.arrayInt(18, i));
  TEST_ASSERT_EQUAL_UINT64(CORE_STEP, d.uint(19));
  TEST_ASSERT_EQUAL_INT64(CORE_HEADX, d.int_(20));
  TEST_ASSERT_EQUAL_INT64(CORE_HEADY, d.int_(21));
  TEST_ASSERT_EQUAL_INT64(CORE_POSX, d.int_(22));
  TEST_ASSERT_EQUAL_INT64(CORE_POSY, d.int_(23));
  TEST_ASSERT_EQUAL_UINT64(CORE_STIMCHANNEL, d.uint(24));
  TEST_ASSERT_EQUAL_UINT64(CORE_STIMPARAM, d.uint(25));
  TEST_ASSERT_EQUAL_UINT64(CORE_STIMSTRENGTH, d.uint(26));
  TEST_ASSERT_EQUAL_UINT64(CORE_STIMUNTIL, d.uint(27));
  // the element past the end and an element of a non-array word read as 0, never out of bounds
  TEST_ASSERT_EQUAL_INT64(0, d.arrayInt(0, CORE_N));
  TEST_ASSERT_EQUAL_INT64(0, d.arrayInt(19, 0));
}

static void test_abi_decode_strings(void) {
  Bytes ret = bytesOf(NAME_RET, sizeof NAME_RET);
  ethtx::AbiDecoder d(ret);
  TEST_ASSERT_EQUAL_STRING(CORE_NAME, d.string(0).c_str());
  Bytes t = bytesOf(TUPLE_RET, sizeof TUPLE_RET);
  ethtx::AbiDecoder e(t);
  TEST_ASSERT_EQUAL_UINT64(42, e.uint(0));
  TEST_ASSERT_TRUE(e.boolean(1));
  TEST_ASSERT_TRUE(e.boolean(0));                 // 42 != 0
  uint8_t a[20]; e.address(2, a);
  TEST_ASSERT_EQUAL_MEMORY(ETH_TEST_ADDR, a, 20);
  TEST_ASSERT_EQUAL_STRING("body", e.string(3).c_str());
  TEST_ASSERT_EQUAL_INT64(-7, e.int_(4));
  uint8_t w[32]; e.bytes32(0, w);
  TEST_ASSERT_EQUAL_HEX8(42, w[31]); TEST_ASSERT_EQUAL_HEX8(0, w[0]);
}

static void test_abi_decode_truncated(void) {
  Bytes empty;
  ethtx::AbiDecoder d(empty);
  TEST_ASSERT_EQUAL_UINT64(0, d.uint(0));
  TEST_ASSERT_EQUAL_INT64(0, d.int_(3));
  TEST_ASSERT_FALSE(d.boolean(0));
  TEST_ASSERT_EQUAL_UINT32(0, d.arrayLen(0));
  TEST_ASSERT_EQUAL_INT64(0, d.arrayInt(0, 0));
  TEST_ASSERT_EQUAL_STRING("", d.string(0).c_str());
  uint8_t a[20]; memset(a, 0xaa, 20); d.address(0, a);
  for (int i = 0; i < 20; i++) TEST_ASSERT_EQUAL_HEX8(0, a[i]);
  // a payload cut in the middle of a string: the decoder returns empty rather than reading past the end
  Bytes cut = bytesOf(NAME_RET, 64 + 8);
  ethtx::AbiDecoder c(cut);
  TEST_ASSERT_EQUAL_STRING("", c.string(0).c_str());
  // a core payload cut inside the v array: the array reads as absent, elements past the cut as 0
  Bytes cutArr = bytesOf(CORE_RET, 28 * 32 + 32 + 10 * 32);
  ethtx::AbiDecoder k(cutArr);
  TEST_ASSERT_EQUAL_UINT32(0, k.arrayLen(0));
  TEST_ASSERT_EQUAL_INT64(CORE_V[9], k.arrayInt(0, 9));
  TEST_ASSERT_EQUAL_INT64(0, k.arrayInt(0, 10));
  TEST_ASSERT_EQUAL_UINT64(CORE_STEP, k.uint(19));
}

// ---------------------------------------------------------------- RLP

static void test_rlp_decode_uint(void) {
  uint8_t a[] = {0x80}, b[] = {0x05}, c[] = {0x82, 0x01, 0x00}, d[] = {0x88, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}, e[] = {0x7f};
  TEST_ASSERT_EQUAL_UINT64(0, ethtx::rlpDecodeUint(bytesOf(a, 1)));
  TEST_ASSERT_EQUAL_UINT64(5, ethtx::rlpDecodeUint(bytesOf(b, 1)));
  TEST_ASSERT_EQUAL_UINT64(256, ethtx::rlpDecodeUint(bytesOf(c, 3)));
  TEST_ASSERT_EQUAL_UINT64(UINT64_MAX, ethtx::rlpDecodeUint(bytesOf(d, 9)));
  TEST_ASSERT_EQUAL_UINT64(127, ethtx::rlpDecodeUint(bytesOf(e, 1)));
  TEST_ASSERT_EQUAL_UINT64(0, ethtx::rlpDecodeUint(Bytes()));
}

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_address_from_private_key);
  RUN_TEST(test_checksum_address);
  RUN_TEST(test_invalid_private_keys);
  RUN_TEST(test_hex);
  RUN_TEST(test_sign_digest_vectors);
  RUN_TEST(test_sign_tx_vectors);
  RUN_TEST(test_sign_tx_default_chain_and_sender);
  RUN_TEST(test_abi_register_body);
  RUN_TEST(test_abi_accept);
  RUN_TEST(test_abi_interaction);
  RUN_TEST(test_abi_commit);
  RUN_TEST(test_abi_stimulate);
  RUN_TEST(test_abi_address_bytes_int);
  RUN_TEST(test_abi_selector);
  RUN_TEST(test_abi_decode_core);
  RUN_TEST(test_abi_decode_strings);
  RUN_TEST(test_abi_decode_truncated);
  RUN_TEST(test_rlp_decode_uint);
  return UNITY_END();
}
