#!/usr/bin/env python3
"""Minimal Minecraft RCON client for the Colony's Paper server (no dependencies).

The password is read from brain/colony/server/rcon.txt (generated by tools/run_server.sh) unless
--password / RCON_PASSWORD is given. The server only listens on 127.0.0.1:25575.

    rcon.py list
    rcon.py 'whitelist add fly1' 'gamerule keepInventory true'
    echo 'say hello' | rcon.py -            # one command per stdin line
    rcon.py --wait 90 list                  # wait up to 90 s for the RCON port to accept the login

As a library:  from rcon import Rcon;  with Rcon() as r: print(r.command("list"))
"""
import argparse
import os
import socket
import struct
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SERVER_DIR = os.path.join(os.path.dirname(HERE), "server")
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 25575

SERVERDATA_AUTH = 3
SERVERDATA_EXECCOMMAND = 2
SERVERDATA_RESPONSE_VALUE = 0


def read_password(path=None):
    path = path or os.path.join(SERVER_DIR, "rcon.txt")
    pw = os.environ.get("RCON_PASSWORD")
    if pw:
        return pw
    with open(path) as f:
        return f.read().strip()


class RconError(Exception):
    pass


class Rcon:
    def __init__(self, host=DEFAULT_HOST, port=DEFAULT_PORT, password=None, timeout=10.0):
        self.host, self.port = host, port
        self.password = password if password is not None else read_password()
        self.timeout = timeout
        self.sock = None
        self._id = 0

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self, *exc):
        self.close()

    def connect(self):
        self.sock = socket.create_connection((self.host, self.port), timeout=self.timeout)
        rid, kind, _ = self._roundtrip(SERVERDATA_AUTH, self.password)
        if rid == -1:
            self.close()
            raise RconError("RCON authentication failed (wrong password?)")

    def close(self):
        if self.sock:
            try:
                self.sock.close()
            finally:
                self.sock = None

    def _send(self, kind, payload):
        self._id = (self._id % 2_000_000_000) + 1
        body = struct.pack("<ii", self._id, kind) + payload.encode("utf-8") + b"\x00\x00"
        self.sock.sendall(struct.pack("<i", len(body)) + body)
        return self._id

    def _recv_exact(self, n):
        buf = b""
        while len(buf) < n:
            chunk = self.sock.recv(n - len(buf))
            if not chunk:
                raise RconError("connection closed by the server")
            buf += chunk
        return buf

    def _recv(self):
        (length,) = struct.unpack("<i", self._recv_exact(4))
        body = self._recv_exact(length)
        rid, kind = struct.unpack("<ii", body[:8])
        return rid, kind, body[8:-2].decode("utf-8", "replace")

    def _roundtrip(self, kind, payload):
        rid = self._send(kind, payload)
        while True:
            r = self._recv()
            # the auth reply is preceded by an empty RESPONSE_VALUE on some servers
            if kind == SERVERDATA_AUTH and r[1] == SERVERDATA_RESPONSE_VALUE and r[0] == rid:
                continue
            return r

    def command(self, cmd):
        """Runs one console command and returns its text response (may be empty).

        Vanilla's RCON closes the socket if two request packets arrive in one read, so the client
        sends one request at a time and reads its reply; replies longer than 4096 bytes arrive as
        several packets with the same id, the last one shorter than 4096.
        """
        rid = self._send(SERVERDATA_EXECCOMMAND, cmd)
        out = []
        while True:
            r_id, r_kind, text = self._recv()
            if r_id != rid:
                continue
            out.append(text)
            if len(text.encode("utf-8")) < 4096:
                break
        return "".join(out)


def wait_for_rcon(seconds, host=DEFAULT_HOST, port=DEFAULT_PORT, password=None):
    """Blocks until an RCON login succeeds or `seconds` elapse. Returns True on success."""
    deadline = time.time() + seconds
    while time.time() < deadline:
        try:
            with Rcon(host, port, password, timeout=3.0):
                return True
        except (OSError, RconError):
            time.sleep(1.0)
    return False


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", default=DEFAULT_HOST)
    ap.add_argument("--port", type=int, default=DEFAULT_PORT)
    ap.add_argument("--password", default=None, help="default: $RCON_PASSWORD or server/rcon.txt")
    ap.add_argument("--wait", type=float, default=0, help="wait up to N seconds for RCON to come up")
    ap.add_argument("commands", nargs="*", help="console commands ('-' reads one per stdin line)")
    a = ap.parse_args(argv)
    password = a.password if a.password is not None else read_password()
    if a.wait and not wait_for_rcon(a.wait, a.host, a.port, password):
        print(f"rcon: {a.host}:{a.port} did not come up within {a.wait:.0f}s", file=sys.stderr)
        return 2
    cmds = []
    for c in a.commands:
        if c == "-":
            cmds += [ln.strip() for ln in sys.stdin if ln.strip() and not ln.lstrip().startswith("#")]
        else:
            cmds.append(c)
    if not cmds:
        ap.print_usage()
        return 1
    try:
        with Rcon(a.host, a.port, password) as r:
            for c in cmds:
                out = r.command(c)
                if out:
                    print(out)
    except (OSError, RconError) as e:
        print(f"rcon: {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
