#!/usr/bin/env python3
"""Generates test/test_screen/fonts_gen.h: the three M5GFX fonts the pebble screen uses (Font0 = the classic 5x7 GLCD
font, Font2 = the 16 px TFT_eSPI font, FreeSansBold12pt7b = the Adafruit GFX font), converted from the M5GFX sources
in .pio/libdeps/cores3/M5GFX so the native renderer (test/test_screen) draws exactly the glyphs the device draws.

    cd firmware && ../.venv/bin/python tools/gen_screen_fonts.py

The generated header is committed: the native test does not need the M5GFX package to build.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.dirname(HERE)
M5 = os.path.join(FW, '.pio', 'libdeps', 'cores3', 'M5GFX', 'src', 'lgfx')
OUT = os.path.join(FW, 'test', 'test_screen', 'fonts_gen.h')


def hexbytes(text):
    return [int(x, 16) for x in re.findall(r'0[xX]([0-9a-fA-F]{1,2})', text)]


def glcd():
    src = open(os.path.join(M5, 'Fonts', 'glcdfont.h')).read()
    body = src[src.index('font[] PROGMEM'):]
    body = body[body.index('{'):body.index('};')]
    data = hexbytes(body)
    assert len(data) >= 127 * 5, len(data)
    return data[32 * 5:127 * 5]   # chars 32..126, 5 column bytes each (bit 0 = top row)


def font16():
    src = open(os.path.join(M5, 'Fonts', 'Font16.h')).read()
    m = re.search(r'widtbl_f16\[96\]\s*=[^{]*\{(.*?)\};', src, re.S)
    body = m.group(1)
    # drop the #ifdef alternative for 0x60 (keep the "grave" variant = the #else branch)
    body = re.sub(r'#ifdef TFT_ESPI_GRAVE_IS_DEGREE.*?#else', '', body, flags=re.S)
    body = body.replace('#endif', '')
    widths = [int(x) for x in re.findall(r'\b(\d+)\b', re.sub(r'//.*', '', body))]
    assert len(widths) == 96, len(widths)
    rows = []
    for c in range(0x20, 0x80):
        mm = re.search(r'chr_f16_%02X\[(\d+)\]\s*=[^{]*\{(.*?)\};' % c, src, re.S)
        body = mm.group(2)
        # the defaults: the GBP sign for 0x24 and the grave accent for 0x60 (the #else branches)
        body = re.sub(r'#ifdef TFT_ESPI_(FONT2_DOLLAR|GRAVE_IS_DEGREE).*?#else', '', body, flags=re.S).replace('#endif', '')
        data = hexbytes(re.sub(r'//.*', '', body))
        bpr = (widths[c - 0x20] + 6) >> 3   # bytes per row, as BMPfont::drawChar reads it
        assert len(data) == 16 * bpr, (c, bpr, len(data))
        for r in range(16):
            v = 0
            for b in range(bpr): v = (v << 8) | data[r * bpr + b]
            if bpr == 1: v <<= 8
            rows.append(v)   # 16-bit row, MSB = leftmost column
    return widths, rows


def gfx():
    src = open(os.path.join(M5, 'Fonts', 'GFXFF', 'FreeSansBold12pt7b.h')).read()
    bm = src[src.index('Bitmaps[] PROGMEM'):]
    bm = bm[bm.index('{'):bm.index('};')]
    bitmaps = hexbytes(bm)
    gl = re.findall(r'\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}', src[src.index('Glyphs[] PROGMEM'):])
    glyphs = [tuple(int(v) for v in g) for g in gl]
    assert len(glyphs) == 95, len(glyphs)
    yadv = int(re.search(r'0x20,\s*0x7E,\s*(\d+)\s*\}', src).group(1))
    ab = max(-g[5] for g in glyphs); bb = max(g[2] + g[5] for g in glyphs)
    return bitmaps, glyphs, yadv, ab, bb


def main():
    if not os.path.isdir(M5):
        sys.exit('M5GFX sources not found at %s (run `pio run -e cores3` once)' % M5)
    f0 = glcd(); w2, r2 = font16(); bmb, glb, yadv, ab, bb = gfx()
    out = []
    out.append('// generated by firmware/tools/gen_screen_fonts.py from the M5GFX font sources (Adafruit GFX / TFT_eSPI fonts,')
    out.append('// BSD licence) so the native screen renderer draws the same glyphs as the device. Do not edit.')
    out.append('#pragma once')
    out.append('#include <stdint.h>')
    out.append('// Font0: 5x7 GLCD font, 6x8 cell, chars 32..126, 5 column bytes each (bit 0 = top row)')
    out.append('static const uint8_t SF0_DATA[%d] = {' % len(f0))
    for i in range(0, len(f0), 20): out.append('  ' + ','.join('0x%02x' % v for v in f0[i:i + 20]) + ',')
    out.append('};')
    out.append('// Font2: 16 px, baseline 13, chars 32..127: advance width per char, glyph drawn in the first width-1 columns')
    out.append('static const uint8_t SF2_W[96] = {' + ','.join(str(v) for v in w2) + '};')
    out.append('static const uint16_t SF2_ROWS[96 * 16] = {   // 16 rows per char, MSB = leftmost column')
    for i in range(0, len(r2), 16): out.append('  ' + ','.join('0x%04x' % v for v in r2[i:i + 16]) + ',')
    out.append('};')
    out.append('// FreeSansBold12pt7b: Adafruit GFX format, chars 32..126')
    out.append('static const int SFB_ASCENT = %d, SFB_DESCENT = %d, SFB_YADVANCE = %d;' % (ab, bb, yadv))
    out.append('struct SfbGlyph { uint16_t off; uint8_t w, h, adv; int8_t xo, yo; };')
    out.append('static const SfbGlyph SFB_GLYPHS[95] = {')
    for g in glb: out.append('  {%d,%d,%d,%d,%d,%d},' % g)
    out.append('};')
    out.append('static const uint8_t SFB_BITMAPS[%d] = {' % len(bmb))
    for i in range(0, len(bmb), 24): out.append('  ' + ','.join('0x%02x' % v for v in bmb[i:i + 24]) + ',')
    out.append('};')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(out) + '\n')
    print('wrote %s: Font0 %d B, Font2 %d rows, big %d glyphs (ascent %d, descent %d, yAdvance %d)' % (OUT, len(f0), len(r2), len(glb), ab, bb, yadv))


if __name__ == '__main__':
    main()
