"""Generate host-test fixtures for the firmware from the reference model.
- fixtures/circuit_table.h : the packed circuit table bytes (== contracts/data/circuit.hex, keccak 0xffbe0e7f…)
- fixtures/params.h        : the deployed v2 parameters
- fixtures/core_fixtures.json : sequences of stimulate/tick actions with the exact expected state after each tick
- fixtures/core_fixtures.h : the same sequences as flat C arrays (so the native Unity test needs no JSON parser)
Run from the repo root:  .venv/bin/python firmware/tools/gen_fixtures.py
"""
import json, os, sys, random
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
sys.path.insert(0, os.path.join(ROOT, 'sim'))
from flysim import Circuit, FlyBrain, CH_CUE, CH_TURN_LEFT, CH_TURN_RIGHT, CH_SHOCK, WEDGES
from Crypto.Hash import keccak
import struct


def state_hash(b):
    """flycore::Core::stateHash: keccak256 of v (int32 LE x N) || bias (int32 LE x N) || hist (u16 LE x 16) || inp (int32 LE x N) || step (u64 LE)."""
    N = b.c.N
    buf = struct.pack(f'<{N}i', *b.v) + struct.pack(f'<{N}i', *b.bias) + struct.pack(f'<{WEDGES}H', *b.hist) + struct.pack(f'<{N}i', *b.inp) + struct.pack('<Q', b.step)
    k = keccak.new(digest_bits=256); k.update(buf); return k.hexdigest()
OUT = os.path.join(ROOT, 'firmware', 'fixtures'); os.makedirs(OUT, exist_ok=True)
hexs = open(os.path.join(ROOT, 'contracts', 'data', 'circuit.hex')).read().strip()
table = bytes.fromhex(hexs[2:] if hexs.startswith('0x') else hexs)
params = json.load(open(os.path.join(ROOT, 'contracts', 'data', 'params.json')))
with open(os.path.join(OUT, 'circuit_table.h'), 'w') as f:
    f.write('// generated by firmware/tools/gen_fixtures.py from contracts/data/circuit.hex — do not edit\n#pragma once\n#include <stdint.h>\n')
    f.write(f'static const unsigned CIRCUIT_TABLE_LEN = {len(table)};\nstatic const uint8_t CIRCUIT_TABLE[{len(table)}] = {{\n')
    for i in range(0, len(table), 24): f.write('  ' + ','.join(f'0x{b:02x}' for b in table[i:i + 24]) + ',\n')
    f.write('};\n')
with open(os.path.join(OUT, 'params.h'), 'w') as f:
    g = ','.join(str(x) for x in params['gains'])
    f.write('// generated from contracts/data/params.json (FlyBrain v2 as deployed) — do not edit\n#pragma once\n#include "flycore.h"\n')
    f.write(f'static const flycore::Params PARAMS_V2 = {{ {params["leak"]}, {params["thresh"]}, {params["reset"]}, {params["vMin"]}, {{{g}}}, {params["gBias"]}, {params["noise"]}, {params["stimGain"]}, {params["stimTTL"]}, {params["walkThreshold"]}, {params["maxSteps"]}, {"true" if params.get("persistInput") else "false"} }};\n')
c = Circuit(table)
rng = random.Random(7)
seqs = []
for s in range(6):
    b = FlyBrain(c, params)
    actions = []
    for k in range(10):
        if rng.random() < 0.6:
            ch = rng.choice([CH_CUE, CH_TURN_LEFT, CH_TURN_RIGHT, CH_SHOCK]); param = rng.randrange(16) if ch == CH_CUE else 0; strength = rng.randrange(1, 9)
            b.stimulate(ch, param, strength); actions.append({'op': 'stimulate', 'channel': ch, 'param': param, 'strength': strength})
        steps = rng.choice([1, 8, 16, 32, 64])
        r = b.tick(steps)
        # copy the state lists: flysim mutates them in place, so a reference would alias every tick's expectation to the final state
        actions.append({'op': 'tick', 'steps': steps, 'expect': {'steps': r['steps'], 'spikes': r['spikes'], 'headX': r['headX'], 'headY': r['headY'], 'posX': r['posX'], 'posY': r['posY'],
                        'v': list(b.v), 'bias': list(b.bias), 'inp': list(b.inp), 'hist': list(b.hist), 'step': b.step, 'totalSpikes': b.totalSpikes,
                        'stateHash': state_hash(b)}})
    seqs.append(actions)
genesis_hash = state_hash(FlyBrain(c, params))
json.dump({'params': params, 'table_len': len(table), 'genesisStateHash': genesis_hash, 'sequences': seqs}, open(os.path.join(OUT, 'core_fixtures.json'), 'w'))

# ---- the same data as C arrays for the native Unity test (no JSON parser on the target toolchain)
# Layout: every action is one FixAction row; tick rows index into flat expectation arrays (v/bias/inp: N per tick, hist: 16 per tick).
N = c.N
ticks = [a for seq in seqs for a in seq if a['op'] == 'tick']
def cjoin(vals, per_line=32):
    lines = []
    vals = list(vals)
    for i in range(0, len(vals), per_line): lines.append('  ' + ','.join(str(x) for x in vals[i:i + per_line]) + ',')
    return '\n'.join(lines) + '\n'
with open(os.path.join(OUT, 'core_fixtures.h'), 'w') as f:
    f.write('// generated by firmware/tools/gen_fixtures.py from sim/flysim.py (FlyBrain v2 params) — do not edit\n')
    f.write('// Replay: for each sequence, apply the actions in order; after every tick compare the whole state with the expectation row.\n')
    f.write('#pragma once\n#include <stdint.h>\n')
    f.write(f'static const int FIX_N = {N};\nstatic const int FIX_WEDGES = {WEDGES};\nstatic const int FIX_SEQUENCES = {len(seqs)};\nstatic const int FIX_TICKS = {len(ticks)};\n')
    f.write('enum FixOp : uint8_t { FIX_STIMULATE = 0, FIX_TICK = 1 };\n')
    f.write('struct FixAction { uint8_t op; uint8_t channel; uint8_t param; uint8_t strength; uint16_t steps; int16_t tick; };  // tick = index into FIX_EXPECT, -1 for stimulate\n')
    f.write('struct FixExpect { uint16_t steps; uint32_t spikes; int32_t headX, headY; int64_t posX, posY; uint64_t step; uint64_t totalSpikes; };\n')
    f.write(f'static const int FIX_SEQ_START[{len(seqs) + 1}] = {{ ')
    starts = [0]
    for seq in seqs: starts.append(starts[-1] + len(seq))
    f.write(', '.join(str(x) for x in starts) + ' };\n')
    f.write(f'static const FixAction FIX_ACTIONS[{starts[-1]}] = {{\n')
    t = 0
    for seq in seqs:
        for a in seq:
            if a['op'] == 'stimulate':
                f.write(f'  {{ FIX_STIMULATE, {a["channel"]}, {a["param"]}, {a["strength"]}, 0, -1 }},\n')
            else:
                f.write(f'  {{ FIX_TICK, 0, 0, 0, {a["steps"]}, {t} }},\n'); t += 1
    f.write('};\n')
    f.write(f'static const FixExpect FIX_EXPECT[{len(ticks)}] = {{\n')
    for a in ticks:
        e = a['expect']
        f.write(f'  {{ {e["steps"]}, {e["spikes"]}u, {e["headX"]}, {e["headY"]}, {e["posX"]}LL, {e["posY"]}LL, {e["step"]}ULL, {e["totalSpikes"]}ULL }},\n')
    f.write('};\n')
    f.write(f'static const int32_t FIX_V[{len(ticks)} * {N}] = {{\n' + cjoin(x for a in ticks for x in a['expect']['v']) + '};\n')
    f.write(f'static const int32_t FIX_BIAS[{len(ticks)} * {N}] = {{\n' + cjoin(x for a in ticks for x in a['expect']['bias']) + '};\n')
    f.write(f'static const int32_t FIX_INP[{len(ticks)} * {N}] = {{\n' + cjoin(x for a in ticks for x in a['expect']['inp']) + '};\n')
    f.write(f'static const uint16_t FIX_HIST[{len(ticks)} * {WEDGES}] = {{\n' + cjoin(x for a in ticks for x in a['expect']['hist']) + '};\n')
    def chash(h): return ','.join(f'0x{h[i:i + 2]}' for i in range(0, 64, 2))
    f.write(f'static const uint8_t FIX_GENESIS_HASH[32] = {{ {chash(genesis_hash)} }};\n')
    f.write(f'static const uint8_t FIX_HASH[{len(ticks)}][32] = {{\n' + ''.join('  { ' + chash(a['expect']['stateHash']) + ' },\n' for a in ticks) + '};\n')
print('wrote', OUT, 'sequences', len(seqs), 'ticks', len(ticks), 'table bytes', len(table))
